[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "17"
  CI = ""

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/cv"
  to = "https://docs.google.com/document/d/1kDilmEm0R1ZrDPrbteFu4i2uX_PZJOQJcjh7l3RRw6o/export?format=pdf"
  status = 302
  
[[redirects]]
  from = "/qr"
  to = "/"
  status = 302