[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/cv"
  to = "https://docs.google.com/document/d/1kDilmEm0R1ZrDPrbteFu4i2uX_PZJOQJcjh7l3RRw6o/export?format=pdf/"
  status = 302
  
[[redirects]]
  from = "/qr"
  to = "/"
  status = 302
  
[[redirects]]
  from = "/qs"
  to = "https://download.teamviewer.com/QS/"
  status = 302

[[redirects]]
  from = "/rd"
  to = "https://rust-desk-exe.musosoft.workers.dev/"
  status = 302
  
[[redirects]]
  from = "/ip"
  to = "https://musosoft.github.io/ip/"
  status = 302
