[build]
  publish = "public"
  command = "yarn build"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs21.x"
  CI = ""
  NODE_VERSION = "21"
  NODE_OPTIONS = "--max-old-space-size= 4096"
  YARN_VERSION = "4.1.1"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/cv"
  to = "https://docs.google.com/document/d/1kDilmEm0R1ZrDPrbteFu4i2uX_PZJOQJcjh7l3RRw6o/export?format=pdf/"
  status = 302
  
[[redirects]]
  from = "/qr"
  to = "/"
  status = 302
  
[[redirects]]
  from = "/qs"
  to = "https://download.teamviewer.com/QS/"
  status = 302
  
[[redirects]]
  from = "/ip"
  to = "https://musosoft.github.io/ip/"
  status = 302
